package:
        name: dep_numpy_a
        version: 1.0.0

requirements:
        build:
                - nomkl
               #- python
                - numpy
        run:
                - nomkl
               #- python
                - numpy

build:
        number: 0
        features:
                - nomkl
