package:
        name: dep_a
        version: 1.0.0

requirements:
        build:
                - feat_1
        run:
                - feat_1

build:
        number: 0
        features:
                - feat_1
